# -*- coding: utf-8 -*-
"""
weather_app.py

Automatically generated by Colaboratory.

"""

pip install requests

import requests, json

api_key = 'bf8229aab7d58c09d6622d4e3074651f'

city = input('Enter city name: ')

url = f'http://api.openweathermap.org/data/2.5/weather?q={city}&appid={api_key}'

response = requests.get(url)

if response.status_code == 200:
    data = response.json()
    temp_kelvin = data['main']['temp']
    temp_celsius = temp_kelvin - 273.15
    desc = data['weather'][0]['description']
    humidity = data['main']['humidity']
    pressure = data['main']['pressure']
    wind = data['wind']['speed']
    print(f'Temperature: {temp_celsius} C')
    print(f'Description: {desc}')
    print(f'Humidity: ',humidity)
    print('Pressure: ',pressure)
    print('Wind:',wind)

else:
    print('Error fetching weather data')
